GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlubiIsImlhdCI6MTY1MTQ5ODU4OSwiZXhwIjoxNjUxNDk4NjA0fQ.yOO0zEX1KLoEetqlQlY1jzvznYL-xwQyC-lYY6a0gKw

###

POST http://localhost:4000/login 
Content-Type: application/json

{
    "username": "Finn"
}

### 

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlubiIsImlhdCI6MTY1MTQ5OTAzMX0.yCRX0mLtxbQ62FedSqBcKbVVosZY-z4ji95gjjHekb4"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlubiIsImlhdCI6MTY1MTQ5OTAzMX0.yCRX0mLtxbQ62FedSqBcKbVVosZY-z4ji95gjjHekb4"
}