GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlubiIsImlhdCI6MTY1MTQ5ODU4OSwiZXhwIjoxNjUxNDk4NjA0fQ.yOO0zEX1KLoEetqlQlY1jzvznYL-xwQyC-lYY6a0gKw

###

POST http://localhost:4000/api/login 
Content-Type: application/json

{
    "email": "emai22444l@em.de",
    "password": "pw123"
}

### 

POST http://localhost:4000/api/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiJ9.ZW1haTIyNDQ0bEBlbS5kZQ.e1oCm2U6RZGUhsXLVRILqtcbm0RJ75t_ZT_0Zzwoa6I"
}

###

DELETE http://localhost:4000/api/logout
Content-Type: application/json

{
    "token":  "eyJhbGciOiJIUzI1NiJ9.ZW1haTIyNDQ0bEBlbS5kZQ.e1oCm2U6RZGUhsXLVRILqtcbm0RJ75t_ZT_0Zzwoa6I"
}

###

POST http://localhost:4000/api/register
Content-Type: application/json

{
    "name": "finn",
    "forename": "finn",
    "email": "finn@test.de",
    "password": "test",
    "city": "bielefeld",
    "postalCode": 33613,
    "street": "bremer straße",
    "telefonNumber": "0123456"
}